Task/Task/Models/CustomerProducts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task.Models
{
    public class CustomerProducts
    {
        public Customer CustomerName { get; set; }
        public PurchaseOrder POID { get; set; }
        public Product ProductName { get; set; }
        public PurchaseOrderDetail Price { get; set; }
    }
}

Task/Task/Models/MaxPriceMonthWise.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task.Models
{
    public class MaxPriceMonthWise
    {
        public DateTime DateOfPurchase { get; set; }
        public PurchaseOrderDetail POID { get; set; }
        public decimal Price { get; set; }
    }
}

Task/Task/Models/MonthWiseCustomerReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task.Models
{
    public class MonthWiseCustomerReport
    {
        public Customer CustomerName { get; set; }
        public DateTime DateOfPurchase { get; set; }
        public PurchaseOrder Amount { get; set; }
    }
}

Task/Task/Models/MonthWiseProductSales.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task.Models
{
    public class MonthWiseProductSales
    {
        public DateTime DateOfPurchase { get; set; }
        public Product ProductName { get; set; }
        public PurchaseOrderDetail Quantity { get; set; }
    }
}

Task/Task/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Task/Task/Controllers/MultipleTablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task.Models;

namespace Task.Controllers
{
    public class MultipleTablesController : Controller
    {
        // GET: MultipleTables
        public ActionResult ListOfPurchaseOrderAgainstCustomer()
        {
            ShoppingEntities iEntity = new ShoppingEntities();
            List<Customer> customers = iEntity.Customers.ToList();
            List<PurchaseOrder> purchaseOrder = iEntity.PurchaseOrders.ToList();
            List<Product> product = iEntity.Products.ToList();
            List<PurchaseOrderDetail> purchaseOrderDetail = iEntity.PurchaseOrderDetails.ToList();
            var Temp = from p in product
                     join pod in purchaseOrderDetail on p.ProductID equals pod.ProductID
                     join po in purchaseOrder on pod.POID equals po.POID
                     join c in customers on po.CustomerID equals c.CustomerID
                     orderby c.CustomerID
                     select new CustomerProducts
                     {
                         CustomerName = c,
                         POID = po,
                         ProductName = p,
                         Price = pod
                     };

            return View(Temp);
        }
        public ActionResult MonthWiseCustomerReportWithProducts()
        {
            ShoppingEntities iEntity = new ShoppingEntities();
            List<Customer> customers = iEntity.Customers.ToList();
            List<PurchaseOrder> purchaseOrder = iEntity.PurchaseOrders.ToList();
            var Temp = from po in purchaseOrder
                     join c in customers on po.CustomerID equals c.CustomerID
                     orderby po.DateOfPurchase.Month
                     select new MonthWiseCustomerReport
                     {
                         CustomerName = c,
                         DateOfPurchase = po.DateOfPurchase,
                         Amount = po
                     };
            return View(Temp);
        }
        public ActionResult ProductSalesReportMonthWise()
        {
            ShoppingEntities iEntity = new ShoppingEntities();
            List<Product> products = iEntity.Products.ToList();
            List<PurchaseOrder> purchaseOrder = iEntity.PurchaseOrders.ToList();
            List<PurchaseOrderDetail> purchaseOrderDetail = iEntity.PurchaseOrderDetails.ToList();
            var Temp = from p in products
                     join po in purchaseOrder on p.ProductID equals po.ProductID
                     join pod in purchaseOrderDetail on po.POID equals pod.POID
                     orderby po.DateOfPurchase.Month
                     select new MonthWiseProductSales
                     {
                         DateOfPurchase = po.DateOfPurchase,
                         ProductName = p,
                         Quantity = pod
                     };
            return View(Temp);
        }
      
    }
}

Task/Task/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task/Task/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task/Task/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Task/Task/Views/MultipleTables/ListOfPurchaseOrderAgainstCustomer.cshtml
@model IEnumerable<Task.Models.CustomerProducts>
@{ ViewBag.Title = "List Of Purchase Order Against Customer"; }
<center>
    <h2>
        List of Purchase order against customer
    </h2>
    <br />
    <br />
    <table class="table table-bordered table-responsive table-hover table-striped">
        <tr>
            <th>Customer Name</th>
            <th>POID</th>
            <th>Product Name</th>
            <th>Price</th>
        </tr>
        @foreach (var item in Model)
        {
<tr>
    <td>@item.CustomerName.CustomerName</td>
    <td>@item.POID.POID</td>
    <td>@item.ProductName.ProductName</td>
    <td>@item.Price.Price</td>
</tr>}
    </table>
</center>

Task/Task/Views/MultipleTables/MonthWiseCustomerReportWithProducts.cshtml
@model IEnumerable<Task.Models.MonthWiseCustomerReport>
@{
    ViewBag.Title = "Month wise Customer Report With Products";
}
<center>
    <h2>
        Monthwise Customer Report With Products
    </h2>
    <br />
    <br />
    <table class="table table-bordered table-responsive table-hover table-striped">
        <tr>
            <th>Month</th>
            <th>Customer Name</th>
            <th>Amount</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DateOfPurchase.ToString("MMMM")- @item.DateOfPurchase.Year</td>
                <td>@item.CustomerName.CustomerName</td>

                <td>@item.Amount.Amount</td>
            </tr>
        }
    </table>
</center>

Task/Task/Views/MultipleTables/ProductSalesReportMonthWise.cshtml
@model IEnumerable<Task.Models.MonthWiseProductSales>
@{
    ViewBag.Title = "Product Sales Report Month Wise";
}
<center>
    <h2>
        Product Sales Report MonthWise
    </h2>
    <br />
    <br />
    <table class="table table-bordered table-responsive table-hover table-striped ">
        <tr>
            <th>Month</th>
            <th>Product Name</th>
            <th>Quantity</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DateOfPurchase.ToString("MMMM")-@item.DateOfPurchase.Year</td>
                <td>@item.ProductName.ProductName</td>

                <td>@item.Quantity.Quantity</td>
            </tr>
        }
    </table>
</center>

Task/Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sopping", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Purchase Order Against Customer", "ListOfPurchaseOrderAgainstCustomer", "MultipleTables")</li>
                    <li>@Html.ActionLink("MonthWise Customer Report", "MonthWiseCustomerReportWithProducts", "MultipleTables")</li>
                    <li>@Html.ActionLink("Product Sales Report", "ProductSalesReportMonthWise", "MultipleTables")</li>
                  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>